export const SAMPLE_ACTION_TYPE = "SAMPLE_ACTION_TYPE";
export const BASE_URL = 'https://cs411-project-273718.uc.r.appspot.com/';

// Auth Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";

// Entry Actions
export const GET_ENTRY_REQUEST = "GET_ENTRY_REQUEST";
export const GET_ENTRY_SUCCESS = "GET_ENTRY_SUCCESS";
export const GET_ENTRY_FAILED = "GET_ENTRY_FAILED";

export const POST_ENTRY_REQUEST = "POST_ENTRY_REQUEST";
export const POST_ENTRY_SUCCESS = "POST_ENTRY_SUCCESS";
export const POST_ENTRY_FAILED = "POST_ENTRY_FAILED";

export const DELETE_ENTRY_REQUEST = "DELETE_ENTRY_REQUEST";
export const DELETE_ENTRY_SUCCESS = "DELETE_ENTRY_SUCCESS";
export const DELETE_ENTRY_FAILED = "DELETE_ENTRY_FAILED";

// Course Actions
export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILED = "GET_COURSE_FAILED";

export const POST_COURSE_REQUEST = "POST_COURSE_REQUEST";
export const POST_COURSE_SUCCESS = "POST_COURSE_SUCCESS";
export const POST_COURSE_FAILED = "POST_COURSE_FAILED";

export const PUT_COURSE_REQUEST = "PUT_COURSE_REQUEST";
export const PUT_COURSE_SUCCESS = "PUT_COURSE_SUCCESS";
export const PUT_COURSE_FAILED = "PUT_COURSE_FAILED";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";

// Instructor Actions
export const GET_INSTRUCTOR_REQUEST = "GET_INSTRUCTOR_REQUEST";
export const GET_INSTRUCTOR_SUCCESS = "GET_INSTRUCTOR_SUCCESS";
export const GET_INSTRUCTOR_FAILED = "GET_INSTRUCTOR_FAILED";

export const POST_INSTRUCTOR_REQUEST = "POST_INSTRUCTOR_REQUEST";
export const POST_INSTRUCTOR_SUCCESS = "POST_INSTRUCTOR_SUCCESS";
export const POST_INSTRUCTOR_FAILED = "POST_INSTRUCTOR_FAILED";

export const PUT_INSTRUCTOR_REQUEST = "PUT_INSTRUCTOR_REQUEST";
export const PUT_INSTRUCTOR_SUCCESS = "PUT_INSTRUCTOR_SUCCESS";
export const PUT_INSTRUCTOR_FAILED = "PUT_INSTRUCTOR_FAILED";

export const DELETE_INSTRUCTOR_REQUEST = "DELETE_INSTRUCTOR_REQUEST";
export const DELETE_INSTRUCTOR_SUCCESS = "DELETE_INSTRUCTOR_SUCCESS";
export const DELETE_INSTRUCTOR_FAILED = "DELETE_INSTRUCTOR_FAILED";

// Match Actions
export const MATCH_COURSES_REQUEST = "MATCH_COURSES_REQUEST";
export const MATCH_COURSES_SUCCESS = "MATCH_COURSES_SUCCESS";
export const MATCH_COURSES_FAILED = "MATCH_COURSES_FAILED";

export const MATCH_INSTRUCTORS_REQUEST = "MATCH_INSTRUCTORS_REQUEST";
export const MATCH_INSTRUCTORS_SUCCESS = "MATCH_INSTRUCTORS_SUCCESS";
export const MATCH_INSTRUCTORS_FAILED = "MATCH_INSTRUCTORS_FAILED";